### ISSUE TITLE
Light bar issue

### ISSUE THREAD

**Issue by Livewithrusty** [Flatracer/VehicleExtraMenu#2]
Currently having an issue when you try to use the vehicle extra menu and police vehicles to add or remove light bars it will not work you can click the box for the extras and nothing happens

**Comment by Flatracer** [comment]
After equipping an extra you have to repair the vehicle for it to be visible.

That is due to the way extras are handles in GTA V and has nothing to do with this resource.

Sorry, I can't help you.
